nomes_bonitos = {
    "BANQUETA": "Banqueta",
    "CAIXA CABIDEIRO": "Caixa para cabideiro",
    "CAIXA PARA LIVROS": "Caixa para livros",
    "PERSIANAS": "Persianas",
    "PIANO ARMARIO": "Piano-armário",
    "VENTILADOR": "Ventilador",
    "VARAL": "Varal",
    "ESTANTE": "Estante",
    "RACK TV": "Rack de TV",
    "SOFA": "Sofá",
    "CADEIRA ESTOFADA": "Cadeira estofada",
    "MESA JANTAR": "Mesa de jantar",
    "SAPATEIRA": "Sapateira",
    "ARMÁRIO COZINHA": "Armário de cozinha",
    "FOGAO": "Fogão",
    "GELADEIRA": "Geladeira",
    "CAMA CASAL": "Cama de casal",
    "COLCHÃO CASAL": "Colchão de casal",
    "CAIXA PARA FERRAMENTAS": "Caixa para ferramentas",
    "COLCHAO CASAL": "Colchão de casal",
    "ESTANTE DE ACO": "Estante de aço",
    "CESTO": "Cesto",
    "MICROONDAS": "Micro-ondas",
    "ESCADA PEQUENA": "Escada pequena",
    "TABUA DE PASSAR": "Tábua de passar"
}